### ISSUE TITLE
SublimeRope is taking a long time in autocomplete 

### ISSUE THREAD

**Issue by bekbulatov** [JulianEberius/SublimeRope#23]
It's taking a lot time when ST is trying to autocomplete. 

I assume it's relevant to empty db index and I don't know how to (re-)generate it. Tried to press [Ctrl-r + Ctrl-c] but it doesn't help. I checked my .ropeproject folder. Files are not so big (if they should be)

`$ ls -l .ropeproject/
-rw-rw-r-- 1 user  3491 Июн 15 12:45 config.py
-rw-rw-r-- 1 user 38753 Июн 15 12:46 globalnames
-rw-rw-r-- 1 user    14 Июн 15 12:30 history
-rw-rw-r-- 1 user     6 Июн 15 12:46 objectdb`

**Comment by glyph** [comment]
I did a little bit of diagnosis on this issue, since completions were starting to get pretty dang slow for me too.  I think the issue is somewhere in the rope library itself (although hopefully Julian can be motivated to contribute a fix upstream :)).

Basically, every time you trigger completion, Sublime Text 2 stat()s a zillion paths; basically everything on your entire project tree.  I suspect that whatever validity- or up-to-date-ness checking is being performed here could be suppressed.

On a mac, you can observe this behavior by doing 'sudo fs_usage $(pgrep Sublime)' and then triggering autocomplete.  On Linux, a similar invocation of strace will do the trick, and I'm assuming that there's something from sysinternals that will show you on Windows (although I'm not entirely sure what).

**Comment by JulianEberius** [comment]
Hi,

Can you check if the most recent version (pushed today) did anything to improve this? 
It should now keep the project opened in memory, instead of reading it from disk on every completion command. 
Beware, this only works for "real" projects, with a .ropeproject directory, not for "instant"-projects.

Julian

**Comment by OscarL** [comment]
Please see #26 as to why the context cache is not working.

**Comment by JulianEberius** [comment]
Fixed #26, thanks.

**Comment by glyph** [comment]
Night and day. It is so much faster now.  I wonder though: do I need to be concerned that the project is never being closed, now?

**Comment by bekbulatov** [comment]
Thank you, after update it became faster but I have another issue. While typing code ST sometimes doesn't respond me for a while. I need to set timeout after that ST will stop looking for. Is there this parameters in settings?

**Comment by JulianEberius** [comment]
Removed another performance problem in 4da4d20befe379c9220927cc35599c8f7f72531b
Closing this old issue now, feel free to file new issues if you still have performance issues.
