### ISSUE TITLE
Bring back "simple module completion"

### ISSUE THREAD

**Issue by OscarL** [JulianEberius/SublimeRope#27]
Hello, please consider the comments on commit e91510b0a2e222c31810e33d1aeea987c1b80176 about why "add_module_directory_completions()" didn't return anything, and why I consider we should get this functionality back.

Thanks.

**Comment by JulianEberius** [comment]
Hi,

I removed it because it seemed to offer little new completions, but reduced performance on large projects. 
I reintroduced it as an optional feature, that you can activate if the performance hit does not bother you. Simply set "use_simple_completions" to True in your User/SublimeRope.sublime-settings.

P.s.: Another strange effect: If you do "import proj" then "from proj." you will get completions from Rope even without the simple module completion activated.

Julian

**Comment by OscarL** [comment]
Thank you.

About your P.S.: yes, I've noticed that too, that's why I want to keep simple_completions at hand, so we can tweak it for just that case :-) (until someone fixes rope proper).
